# import = ["~/.config/alacritty/rose-pine-moon.toml"]
import = ["~/.config/alacritty/one-dark.toml"]

[font]
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
size = 12.4

[window]
padding = { x = 3, y = 3 }

[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "On" }
